[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
logos = {version = "0.12.0", optional = true}
thiserror = "1.0.30"

[features]
default = ["scanner_clike"]

scanner_clike = []
scanner_rusty = []
scanner_logos = ["dep:logos"]
