[package]
edition = "2021"
name = "rlox"
version = "0.1.0"

[dependencies]
lazy_static = "1.4.0"
logos = {version = "0.12.0", optional = true}
thiserror = "1.0.30"

[features]
default = ["scanner_recursive_descent"]

scanner_logos = ["dep:logos"]
scanner_recursive_descent = []
